---
# Copyright 2017 Charter DNA Team (CTEC).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: creating new instances and attaching to declared networks
  os_server:
       state: "{{ instance_os_status }}"
       auth:
         auth_url: "{{ auth_os_auth_url }}"
         username: "{{ auth_os_username }}"
         password: "{{ auth_os_password }}"
         project_name: "{{ project_os_project }}"
       name: "{{ instance_os_hostname }}-{{ item }}"
       image: "{{ instance_os_image_id }}"
       key_name: "{{ instance_os_key_name }}"
       timeout: 200
       flavor: "{{ instance_os_flavor_id }}"
       network: "{{ network_os_network_id }}"
       meta:
         hostname: "{{ meta_os_hostname }}"
         group: "{{ meta_os_group }}"
  with_sequence: "start=1 end={{ instance_os_count }} format=%02x"
